server.port=8082
spring.application.name=order-service

# Register with Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/micro_order_db
spring.datasource.username=root
spring.datasource.password=Karthick@#2005

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Force full stack traces to print in Eclipse console
logging.level.org.springframework.web=DEBUG
logging.level.com.example.order_service=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.feign=DEBUG